### PR TITLE
Pledge Drive Countdown 

### PR DESCRIPTION
**Pull request by binerys**
A WIP of our countdown timer
Currently following this tutorial: http://codepen.io/SitePoint/pen/MwNPVq

### CODE REVIEW

**Comment by binerys** [comment]
@kianadk Something weird happens and looks like this branch now contains former commits from the events panel. I think we might to restart this pull request/branch and start fresh or else we might mess up the commit history. 

So I would just copy over the relevant files you modified and do following: 
```
git checkout master
git pull # Update master to latest version
git checkout -b countdown-timer # or some other name lol
# Update the files modified and commit 
# Push new branch and open PR
```

But this is awesome and thank you for helping me out 😭

**Comment by kianadk** [comment]
screen shot 2017-04-20 at 2 47 52 pm
We have a working countdown timer!

**Comment by kianadk** [comment]
Ahh sorry about that, I think I was still all messed up from the merge conflicts we were dealing with on Friday and I must have done something dumb. But I moved the changes to a new branch here: https://github.com/uclaradio/uclaradio/pull/107

**Comment by binerys** [comment]
Closing due to commit conflicts

**Pull request closed without merging**
