### PR TITLE
Chat feature 

### PR DESCRIPTION
**Pull request by hsuregan**
highlights -

* **listeners will now be able to chat to radio hosts on air, to each other, and see what other listeners are talking about**
* current song animation added to let listeners know which song is currently playing
* 'show recent tracks' has been replaced with a symbol
--------

**_My plan is to roll this out before programming begins_**

image
image
image
image
image

### CODE REVIEW

**Comment by ChrisLaganiere** [comment]
So cool!! Looks great to me. I just added the npm packages I had to install to build

**Comment by hsuregan** [comment]
Actualllly :1st_place_medal: @ChrisLaganiere :1st_place_medal: can you handle the merging of this branch into master?

**Comment by hsuregan** [comment]
@ChrisLaganiere actually ill give it a try .....

**Comment by hsuregan** [comment]
ok i resolved the conflicts horaaay
@ChrisLaganiere @kianadk @binerys if yall have any questions/ want to make changes -- comment/let me know/make them! Before I merge this into master

**Pull request merged**
