### PR TITLE
Dj list

### PR DESCRIPTION
**Pull request by binerys**
screen shot 2016-11-16 at 6 18 37 pm

### CODE REVIEW

**Comment by binerys** [comment]
screen shot 2016-11-16 at 6 47 54 pm

Updated to circle image for profiles

**Comment by hsuregan** [comment]
@binerys  looks great so far!
can we make the thumbnails center on mobile?

**Comment by hsuregan** [comment]
@binerys @nmockovciak wait I was thinking since we are going for square-ey design, that we should probably stick with squares for the DJ thumbnails ? What do y'all think

**Comment by hsuregan** [comment]
@ChrisLaganiere

**Comment by ChrisLaganiere** [comment]
We like the circles @hsuregan at least we should keep it the same as the app

**Comment by ChrisLaganiere** [comment]
Looks awesome @binerys I will integrate it with react-router soon and I think it's ready to merge if @hsuregan gives a 👍 

I replaced the default picture and centered the list:

screen shot 2016-11-20 at 7 17 40 pm

**Comment by hsuregan** [comment]
@binerys @ChrisLaganiere Looks good to me

**Pull request closed without merging**
